# Development environment
name: tk-app

services:
  app:
    build:
      context: .
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_LOCAL_PORT:-80}:80"
      - "${HTTPS_LOCAL_PORT:-443}:443"
      - "${HTTPS_LOCAL_PORT:-443}:443/udp"
    # comment out for ssl on production...
    entrypoint: ["frankenphp"]
    command: ["php-server", "--root=/app/public", "--listen=:80"]
    volumes:
      - ./app:/app
      - ./app/docker/php.ini:/usr/local/etc/php/conf.d/overrides.ini
    environment:
      SERVER_NAME: "${SERVER_NAME:-localhost}"

  mailpit:
    # mailpit wont shutdown with a profile ?????
    # PhpStorm issue, docker compose down does not have a profile flag
#    profiles: [ "local" ]
    image: axllent/mailpit
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mailpit:/data
    ports:
      - "${MAILPIT_HTTP_PORT:-8025}:8025" # Web UI
      - "${MAILPIT_SMTP_PORT:-1025}:1025" # SMTP server
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  queue:
    build:
      context: .
    volumes:
      - ./app:/app
    entrypoint: ["php"]
    command: ["/app/artisan", "queue:work", "--verbose", "--tries=5", "--timeout=90", "--sleep=3"]
    restart: unless-stopped

  composer:
    profiles: [ "prod" ]
    image: composer:latest
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app
    entrypoint: [ "composer" ]
    command: [ "install", "--no-interaction", "--prefer-dist" ]
    restart: "no"

  artisan:
    profiles: [ "prod" ]
    build:
      context: .
    tty: true
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: [ "php" ]
    command: [ "artisan", "app:update" ]
    depends_on:
      composer:
        condition: service_completed_successfully
    restart: "no"

  migrate:
    profiles: [ "prod" ]
    build:
      context: .
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    depends_on:
      artisan:
        condition: service_completed_successfully
    entrypoint: ["php"]
    command: [
      "/app/artisan",
      "migrate",
      "--no-ansi",
      "--force"
    ]
    restart: "no"

# Networks
# ggl: Docker comose with macvlan
# ggl: Docker comose with ipvlan
# ggl: Docker comose with ipvlan l3
