# TODO: Use a single compose file for dev/prod when phpStorm sorts its profile tags out.

# Production
name: ${APP_NAME:-tk-app}

services:
  app:
    build:
      context: ..
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
      - "${HTTPS_PORT:-443}:443/udp"
    volumes:
      - db:/app/database/storage
      - storage:/app/storage
      - ./app/docker/php.ini:/usr/local/etc/php/conf.d/overrides.ini
    networks:
      - network
    environment:
      SERVER_NAME: "${SERVER_NAME:-localhost}"

  queue:
    build:
      context: ..
    volumes:
      - .:/app
    entrypoint: ["php"]
    command: ["/app/artisan", "queue:work", "--verbose", "--tries=5", "--timeout=90", "--sleep=3"]
    restart: unless-stopped
    networks:
      - network

  composer:
    image: composer:latest
    working_dir: /app
    tty: true
    volumes:
      - .:/app
    entrypoint: [ "composer" ]
    command: [ "install", "--no-interaction", "--prefer-dist" ]
    restart: "no"
    networks:
      - network

  artisan:
    build:
      context: ..
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ "php" ]
    command: [ "artisan", "app:update" ]
    depends_on:
      composer:
        condition: service_completed_successfully
    restart: "no"
    networks:
      - network

  migrate:
    build:
      context: ..
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    depends_on:
      artisan:
        condition: service_completed_successfully
    entrypoint: ["php"]
    command: [
      "/app/artisan",
      "migrate",
      "--no-ansi",
      "--force"
    ]
    restart: "no"
    networks:
      - network

volumes:
  db:
  storage:

networks:
  network:
    driver: bridge
