# Production environment
name: ${APP_NAME}-prod

services:
  app:
    build:
      context: .
    container_name: ${APP_NAME}
    tty: true
    restart: always
    ports:
      - "8080:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - db:/app/database/storage
      - storage:/app/storage
      - ./docker/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_LEVEL: debug
      APP_URL: "https://${DOMAIN:-localhost}/"
      APP_KEY: "${APP_KEY}"


  composer:
    #    profiles: [ "tools" ]
    image: composer:latest
    working_dir: /app
    tty: true
    volumes:
      - ./app:/app
    entrypoint: [ "composer" ]
    command: [ "install", "--no-interaction", "--prefer-dist" ]
    restart: "no"

  artisan:
#    profiles: [ "tools" ]
    build:
      context: .
      dockerfile: app/Dockerfile
    tty: true
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: [ "php" ]
    command: [ "artisan", "app:update" ]
    depends_on:
      composer:
        condition: service_completed_successfully
    restart: "no"

  migrate:
    #    profiles: [ "tools" ]
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    depends_on:
      #      artisan:
      composer:
        condition: service_completed_successfully
    entrypoint: ["php"]
    command: [
      "/app/artisan",
      "migrate",
      "--no-ansi",
      "--force"
    ]
    restart: "no"


volumes:
  db:
  storage:


